// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW6yRMu9kR66P4HT8ee32BCO0mbDZGFU4',
    appId: '1:881932875311:web:02bdb6cc39d3b8395c38da',
    messagingSenderId: '881932875311',
    projectId: 'iot-agriculture-e4409',
    authDomain: 'iot-agriculture-e4409.firebaseapp.com',
    databaseURL: 'https://iot-agriculture-e4409-default-rtdb.firebaseio.com',
    storageBucket: 'iot-agriculture-e4409.firebasestorage.app',
    measurementId: 'G-QEQJKY0CTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOVD14XTaIBNdyNydFRCTmnV4-mpuzXMo',
    appId: '1:881932875311:android:4a21b967ccb2efae5c38da',
    messagingSenderId: '881932875311',
    projectId: 'iot-agriculture-e4409',
    databaseURL: 'https://iot-agriculture-e4409-default-rtdb.firebaseio.com',
    storageBucket: 'iot-agriculture-e4409.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPOcMadlSwWDpTKOW2e4XTpgQe0PBXvEc',
    appId: '1:881932875311:ios:393f2863f349e7075c38da',
    messagingSenderId: '881932875311',
    projectId: 'iot-agriculture-e4409',
    databaseURL: 'https://iot-agriculture-e4409-default-rtdb.firebaseio.com',
    storageBucket: 'iot-agriculture-e4409.firebasestorage.app',
    iosBundleId: 'com.example.iotAgricultureApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPOcMadlSwWDpTKOW2e4XTpgQe0PBXvEc',
    appId: '1:881932875311:ios:393f2863f349e7075c38da',
    messagingSenderId: '881932875311',
    projectId: 'iot-agriculture-e4409',
    databaseURL: 'https://iot-agriculture-e4409-default-rtdb.firebaseio.com',
    storageBucket: 'iot-agriculture-e4409.firebasestorage.app',
    iosBundleId: 'com.example.iotAgricultureApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW6yRMu9kR66P4HT8ee32BCO0mbDZGFU4',
    appId: '1:881932875311:web:15945f71429817185c38da',
    messagingSenderId: '881932875311',
    projectId: 'iot-agriculture-e4409',
    authDomain: 'iot-agriculture-e4409.firebaseapp.com',
    databaseURL: 'https://iot-agriculture-e4409-default-rtdb.firebaseio.com',
    storageBucket: 'iot-agriculture-e4409.firebasestorage.app',
    measurementId: 'G-78EK93TLJT',
  );
}
